# assets_manifest.py - The safe storage for all static URLs

STATIC_ASSETS = {
"4WDOUTSIDECAFE": "https://storage.googleapis.com/remys-digest-public-assets/static/4WD Outside Cafe.jpg",
"4WDONCURB": "https://storage.googleapis.com/remys-digest-public-assets/static/4WD on Curb.jpg",
"ACADEMICPORTRAIT": "https://storage.googleapis.com/remys-digest-public-assets/static/Academic Portrait.jpg",
"ACCESSORYFOCUS": "https://storage.googleapis.com/remys-digest-public-assets/static/Accessory Focus.jpg",
"AGINGBOXERINSMOKINGJACKET": "https://storage.googleapis.com/remys-digest-public-assets/static/Aging Boxer in Smoking Jacket.jpg",
"ANGRYSTANDINGCLOWNDACHSHUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Angry Standing Clown Dachshund.png",
"ANGRYSTANDINGDACHSHUNDPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Angry Standing Dachshund Pose.jpg",
"ANTHROPOMORPHICRATDESIGN": "https://storage.googleapis.com/remys-digest-public-assets/static/Anthropomorphic Rat Design.jpg",
"ANTHROPOMORPHISMINLIGNECLAIRE": "https://storage.googleapis.com/remys-digest-public-assets/static/Anthropomorphism in Ligne Claire.jpg",
"AQUARIUSCONCEPTEXAMPLE": "https://storage.googleapis.com/remys-digest-public-assets/static/Aquarius Concept Example.jpg",
"ARCHITECTIBIS": "https://storage.googleapis.com/remys-digest-public-assets/static/Architect Ibis.jpg",
"ARIESCONCEPT": "https://storage.googleapis.com/remys-digest-public-assets/static/Aries Concept.jpg",
"BADLYPARKED4WD": "https://storage.googleapis.com/remys-digest-public-assets/static/Badly Parked 4WD.jpg",
"BALANCING_ACTIONPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Balancing_Action Pose.jpg",
"BASEANTHROPOMORPHICIBISPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Base Anthropomorphic Ibis Pose.jpg",
"BASSETHOUNDINSWEATERVEST": "https://storage.googleapis.com/remys-digest-public-assets/static/Basset Hound in Sweater Vest.jpg",
"BEAGLEWHEELIE": "https://storage.googleapis.com/remys-digest-public-assets/static/Beagle Wheelie.png",
"BINSONADELINEATEDCURB": "https://storage.googleapis.com/remys-digest-public-assets/static/Bins on a Delineated Curb.jpg",
"BIRDKILLFEATHERS1": "https://storage.googleapis.com/remys-digest-public-assets/static/Bird Kill Feathers 1.png",
"BIRDKILLFEATHERS2": "https://storage.googleapis.com/remys-digest-public-assets/static/Bird Kill Feathers 2.png",
"BIRDKILLFEATHERS4": "https://storage.googleapis.com/remys-digest-public-assets/static/Bird Kill Feathers 4.png",
"BLACK4WDFACINGCAFE": "https://storage.googleapis.com/remys-digest-public-assets/static/Black 4WD Facing Cafe.png",
"BLACKANDTANCLOWN": "https://storage.googleapis.com/remys-digest-public-assets/static/Black and Tan Clown.png",
"BLACKANDTANCONTRAST": "https://storage.googleapis.com/remys-digest-public-assets/static/Black and Tan Contrast.jpg",
"BLUESUITANDREDTIE": "https://storage.googleapis.com/remys-digest-public-assets/static/Blue Suit and Red Tie.jpg",
"BOLDGEOMETRICSKIPBIN": "https://storage.googleapis.com/remys-digest-public-assets/static/Bold Geometric Skip Bin.jpg",
"BUMPERTOBUMPERFRUSTRATION": "https://storage.googleapis.com/remys-digest-public-assets/static/Bumper-to-Bumper Frustration.jpg",
"CARDBOARDBOXSTACKS": "https://storage.googleapis.com/remys-digest-public-assets/static/Cardboard Box Stacks.jpg",
"CARTOONPOLICEMAN": "https://storage.googleapis.com/remys-digest-public-assets/static/Cartoon Policeman.png",
"CHEFIBIS": "https://storage.googleapis.com/remys-digest-public-assets/static/Chef Ibis.jpg",
"CLASSICLIGNECLAIREBIN": "https://storage.googleapis.com/remys-digest-public-assets/static/Classic Ligne Claire Bin.jpg",
"CLEARLINESTYLEEXAMPLE": "https://storage.googleapis.com/remys-digest-public-assets/static/Clear Line Style Example.jpg",
"CLOWNDACHSHUNDPORTRAIT": "https://storage.googleapis.com/remys-digest-public-assets/static/Clown Dachshund Portrait.png",
"COLLAPSINGSOGGYBOX": "https://storage.googleapis.com/remys-digest-public-assets/static/Collapsing Soggy Box.jpg",
"CONFIDENTLEANINGPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Confident Leaning Pose.jpg",
"CORGIWHEELIE": "https://storage.googleapis.com/remys-digest-public-assets/static/Corgi Wheelie.png",
"COSTUMESCALEHUMOR": "https://storage.googleapis.com/remys-digest-public-assets/static/Costume Scale Humor.jpg",
"CROSSEDARMSDISDAIN": "https://storage.googleapis.com/remys-digest-public-assets/static/Crossed Arms Disdain.jpg",
"DACHSHUNDCHARACTERDESIGN": "https://storage.googleapis.com/remys-digest-public-assets/static/Dachshund Character Design.jpg",
"DACHSHUNDFACESTYLIZATION": "https://storage.googleapis.com/remys-digest-public-assets/static/Dachshund Face Stylization.jpg",
"DACHSHUNDSHOUTINGPROFILE": "https://storage.googleapis.com/remys-digest-public-assets/static/Dachshund Shouting Profile.jpg",
"DACHSHUNDSNARLDETAIL": "https://storage.googleapis.com/remys-digest-public-assets/static/Dachshund Snarl Detail.jpg",
"DETECTIVEIBIS": "https://storage.googleapis.com/remys-digest-public-assets/static/Detective Ibis.jpg",
"DINERCOUNTERCOMPLAINT": "https://storage.googleapis.com/remys-digest-public-assets/static/Diner Counter Complaint.jpg",
"DIVERSECATBODYSHAPES": "https://storage.googleapis.com/remys-digest-public-assets/static/Diverse Cat Body Shapes.jpg",
"DYNAMICANGRYDACHSHUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Dynamic Angry Dachshund.jpg",
"DYNAMICCLOWNDACHSHUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Dynamic Clown Dachshund.png",
"DYNAMICOUTLINESTUDY": "https://storage.googleapis.com/remys-digest-public-assets/static/Dynamic Outline Study.jpg",
"DYNAMICPLAYERACTION": "https://storage.googleapis.com/remys-digest-public-assets/static/Dynamic Player Action.jpg",
"EXAGGERATEDPUGRANTFACE": "https://storage.googleapis.com/remys-digest-public-assets/static/Exaggerated Pug Rant Face.jpg",
"EXAGGERATEDSHOCKEXPRESSION": "https://storage.googleapis.com/remys-digest-public-assets/static/Exaggerated Shock Expression.jpg",
"EXASPERATEDDRIVERPORTRAIT": "https://storage.googleapis.com/remys-digest-public-assets/static/Exasperated Driver Portrait.jpg",
"FRUSTRATEDHANDSUPGESTURE": "https://storage.googleapis.com/remys-digest-public-assets/static/Frustrated Hands Up Gesture.jpg",
"FULLCLOWNDACHSHUNDWITHBEAR": "https://storage.googleapis.com/remys-digest-public-assets/static/Full Clown Dachshund with Bear.png",
"FURIOUSCLOWNDACHSHUND1": "https://storage.googleapis.com/remys-digest-public-assets/static/Furious Clown Dachshund (1).png",
"FURIOUSCLOWNDACHSHUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Furious Clown Dachshund.png",
"FURIOUSDACHSHUNDCLOSEUP": "https://storage.googleapis.com/remys-digest-public-assets/static/Furious Dachshund Close-up.jpg",
"GARAGERANTABOUTBROKENMACHINERY": "https://storage.googleapis.com/remys-digest-public-assets/static/Garage Rant about Broken Machinery.jpg",
"GEMINICONCEPT": "https://storage.googleapis.com/remys-digest-public-assets/static/Gemini Concept.jpg",
"GEMINI_GENERATED_IMAGE_3YLVQW3YLVQW3YLV": "https://storage.googleapis.com/remys-digest-public-assets/static/Gemini_Generated_Image_3ylvqw3ylvqw3ylv.png",
"GEMINI_GENERATED_IMAGE_4PNDG34PNDG34PND": "https://storage.googleapis.com/remys-digest-public-assets/static/Gemini_Generated_Image_4pndg34pndg34pnd.png",
"GESTUREPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Gesture Pose.jpg",
"GIANTSATURATEDCARDBOARDBOX": "https://storage.googleapis.com/remys-digest-public-assets/static/Giant Saturated Cardboard Box.jpg",
"GREYSUITANDAVIATORS1": "https://storage.googleapis.com/remys-digest-public-assets/static/Grey Suit and Aviators (1).jpg",
"GREYSUITANDAVIATORS": "https://storage.googleapis.com/remys-digest-public-assets/static/Grey Suit and Aviators.jpg",
"GROUPWALKINGPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Group Walking Pose.jpg",
"GRUMPYMALTESEWITHSPECS": "https://storage.googleapis.com/remys-digest-public-assets/static/Grumpy Maltese with Specs.jpg",
"HANDDRAWNFLATSTYLE": "https://storage.googleapis.com/remys-digest-public-assets/static/Hand-Drawn Flat Style.jpg",
"HEADLESSDEADMOUSE1": "https://storage.googleapis.com/remys-digest-public-assets/static/Headless Dead Mouse 1.png",
"HEADLESSDEADMOUSE2": "https://storage.googleapis.com/remys-digest-public-assets/static/Headless Dead Mouse 2.png",
"HEADLESSDEADMOUSE3": "https://storage.googleapis.com/remys-digest-public-assets/static/Headless Dead Mouse 3.png",
"HEADLESSDEADMOUSE4": "https://storage.googleapis.com/remys-digest-public-assets/static/Headless Dead Mouse 4.png",
"HEADWEAROPTIONS": "https://storage.googleapis.com/remys-digest-public-assets/static/Headwear Options.jpg",
"HEAVYOUTLINELIGNECLAIRE": "https://storage.googleapis.com/remys-digest-public-assets/static/Heavy Outline Ligne Claire.jpg",
"HIGHCONTRASTDUMPSTER": "https://storage.googleapis.com/remys-digest-public-assets/static/High Contrast Dumpster.jpg",
"HUSKYRIDING": "https://storage.googleapis.com/remys-digest-public-assets/static/Husky Riding.png",
"IMPATIENTPOSTALOFFICELINE": "https://storage.googleapis.com/remys-digest-public-assets/static/Impatient Postal Office Line.jpg",
"INDUSTRIALSKIPBINOVERFLOW": "https://storage.googleapis.com/remys-digest-public-assets/static/Industrial Skip Bin Overflow.jpg",
"INFINITEGRIDLOCK": "https://storage.googleapis.com/remys-digest-public-assets/static/Infinite Gridlock.jpg",
"JESTERDACHSHUNDFULLBODY": "https://storage.googleapis.com/remys-digest-public-assets/static/Jester Dachshund Full Body.png",
"LEANINGDILAPIDATEDSHED": "https://storage.googleapis.com/remys-digest-public-assets/static/Leaning Dilapidated Shed.jpg",
"LECTUREHALLPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Lecture Hall Pose.jpg",
"LEOCONCEPTDOGONLY": "https://storage.googleapis.com/remys-digest-public-assets/static/Leo Concept (Dog Only).jpg",
"LIGNECLAIREDETAIL": "https://storage.googleapis.com/remys-digest-public-assets/static/Ligne Claire Detail.jpg",
"LOWANGLESOGGYBOXVIEW": "https://storage.googleapis.com/remys-digest-public-assets/static/Low-Angle Soggy Box View.jpg",
"MAILCARRIERONDUTY": "https://storage.googleapis.com/remys-digest-public-assets/static/Mail Carrier on Duty.jpg",
"MISCHIEVOUSCATEXPRESSION": "https://storage.googleapis.com/remys-digest-public-assets/static/Mischievous Cat Expression.jpg",
"MOUSEANDSCATTEREDFEATHERS": "https://storage.googleapis.com/remys-digest-public-assets/static/Mouse and Scattered Feathers.jpg",
"NETBALLPOSTDETAILCORRECTED": "https://storage.googleapis.com/remys-digest-public-assets/static/Netball Post Detail Corrected.png",
"NETBALLPOSTDETAIL": "https://storage.googleapis.com/remys-digest-public-assets/static/Netball Post Detail.jpg",
"NEWCRITICEYEPATCHCARTOON": "https://storage.googleapis.com/remys-digest-public-assets/static/New Critic Eye Patch (Cartoon).png",
"NEWSBOYATTIRE": "https://storage.googleapis.com/remys-digest-public-assets/static/Newsboy Attire.jpg",
"NEWSPAPEREDITORLOOK": "https://storage.googleapis.com/remys-digest-public-assets/static/Newspaper Editor Look.jpg",
"NEWSPAPERPORCHCOMPLAINT": "https://storage.googleapis.com/remys-digest-public-assets/static/Newspaper Porch Complaint.jpg",
"OVERFLOWINGSTREETBINCASCADE": "https://storage.googleapis.com/remys-digest-public-assets/static/Overflowing Street Bin Cascade.jpg",
"PERSPECTIVEPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Perspective Pose.jpg",
"PISCESCONCEPTDOGONLY": "https://storage.googleapis.com/remys-digest-public-assets/static/Pisces Concept (Dog Only).jpg",
"POIGNANTSOLOSCENE": "https://storage.googleapis.com/remys-digest-public-assets/static/Poignant Solo Scene.jpg",
"POLITICIANSUIT": "https://storage.googleapis.com/remys-digest-public-assets/static/Politician Suit.jpg",
"POWERPOSE": "https://storage.googleapis.com/remys-digest-public-assets/static/Power Pose.jpg",
"PRESENTATIONMOCKUPTILE": "https://storage.googleapis.com/remys-digest-public-assets/static/Presentation Mockup Tile.jpg",
"PROFESSORDACHSHUNDDESKSCENE": "https://storage.googleapis.com/remys-digest-public-assets/static/Professor Dachshund Desk Scene.jpg",
"PROFESSORIBIS": "https://storage.googleapis.com/remys-digest-public-assets/static/Professor Ibis.jpg",
"PROFILEOFDISAPPROVAL": "https://storage.googleapis.com/remys-digest-public-assets/static/Profile of Disapproval.jpg",
"RED4WDFACINGCAFE": "https://storage.googleapis.com/remys-digest-public-assets/static/Red 4WD Facing Cafe.png",
"REFEREEANDACCESSORIES": "https://storage.googleapis.com/remys-digest-public-assets/static/Referee and Accessories.jpg",
"RETRO1950SFLATSTYLE": "https://storage.googleapis.com/remys-digest-public-assets/static/Retro 1950s Flat Style.jpg",
"RUSTYMETALSHED": "https://storage.googleapis.com/remys-digest-public-assets/static/Rusty Metal Shed.jpg",
"SCORPIOCONCEPT": "https://storage.googleapis.com/remys-digest-public-assets/static/Scorpio Concept.jpg",
"SCOTTISHTERRIERPOSESHEET": "https://storage.googleapis.com/remys-digest-public-assets/static/Scottish Terrier Pose Sheet.jpg",
"SHEDWITHCOLLAPSINGROOF": "https://storage.googleapis.com/remys-digest-public-assets/static/Shed with Collapsing Roof.jpg",
"SHOUTINGCLOWNPROFILE": "https://storage.googleapis.com/remys-digest-public-assets/static/Shouting Clown Profile.png",
"SNARLINGCLOWNDACHSHUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Snarling Clown Dachshund.png",
"SPANIELRIDINGFATTIREEBIKE": "https://storage.googleapis.com/remys-digest-public-assets/static/Spaniel Riding Fat-Tire E-Bike.png",
"STAGESOFCARDBOARDDECAY": "https://storage.googleapis.com/remys-digest-public-assets/static/Stages of Cardboard Decay.jpg",
"STATICPLAYERSPOSES": "https://storage.googleapis.com/remys-digest-public-assets/static/Static Players Poses.jpg",
"STICKINAMUDMOUND": "https://storage.googleapis.com/remys-digest-public-assets/static/Stick in a Mud Mound.jpg",
"TAURUSCONCEPT": "https://storage.googleapis.com/remys-digest-public-assets/static/Taurus Concept.jpg",
"THEARTISTICCATPAINTER": "https://storage.googleapis.com/remys-digest-public-assets/static/The Artistic Cat Painter.jpg",
"THECUTTHROAT": "https://storage.googleapis.com/remys-digest-public-assets/static/The Cut Throat.jpg",
"THEFATCATGENTLEMAN": "https://storage.googleapis.com/remys-digest-public-assets/static/The Fat Cat Gentleman.jpg",
"THEGRAFFITIARTIST": "https://storage.googleapis.com/remys-digest-public-assets/static/The Graffiti Artist.jpg",
"THEMIXOLOGIST": "https://storage.googleapis.com/remys-digest-public-assets/static/The Mixologist.jpg",
"THEREALESTATEAGENT": "https://storage.googleapis.com/remys-digest-public-assets/static/The Real Estate Agent.jpg",
"THESLYCATAGENT": "https://storage.googleapis.com/remys-digest-public-assets/static/The Sly Cat Agent.jpg",
"THETHIEF": "https://storage.googleapis.com/remys-digest-public-assets/static/The Thief.jpg",
"THETRADESMANMECHANIC": "https://storage.googleapis.com/remys-digest-public-assets/static/The Tradesman (Mechanic).png",
"THETRADESMANPLUMBER": "https://storage.googleapis.com/remys-digest-public-assets/static/The Tradesman (Plumber).png",
"THETRADESMANWELDER": "https://storage.googleapis.com/remys-digest-public-assets/static/The Tradesman (Welder).jpg",
"THICKSTICKINCRACKEDMUD": "https://storage.googleapis.com/remys-digest-public-assets/static/Thick Stick in Cracked Mud.jpg",
"THREEBINSCOMPOSITION": "https://storage.googleapis.com/remys-digest-public-assets/static/Three Bins Composition.jpg",
"TINTINSTYLEDETECTIVE": "https://storage.googleapis.com/remys-digest-public-assets/static/Tintin Style Detective.jpg",
"TOADFACEWITHSUNGLASSESFOCUS": "https://storage.googleapis.com/remys-digest-public-assets/static/Toad Face with Sunglasses Focus.jpg",
"TRAFFICJAMPROPS": "https://storage.googleapis.com/remys-digest-public-assets/static/Traffic Jam Props.jpg",
"TUXEDOFORMALWEAR": "https://storage.googleapis.com/remys-digest-public-assets/static/Tuxedo Formal Wear.jpg",
"VARYINGTOADSHAPES": "https://storage.googleapis.com/remys-digest-public-assets/static/Varying Toad Shapes.jpg",
"VIRGOCONCEPT1": "https://storage.googleapis.com/remys-digest-public-assets/static/Virgo Concept (1).jpg",
"VIRGOCONCEPT": "https://storage.googleapis.com/remys-digest-public-assets/static/Virgo Concept.jpg",
"WHITE4WDFACINGCAFE": "https://storage.googleapis.com/remys-digest-public-assets/static/White 4WD Facing Cafe.png",
"WHITESHOESDETAIL": "https://storage.googleapis.com/remys-digest-public-assets/static/White Shoes Detail.jpg",
"WIREMESHBINANDREFLECTIONS": "https://storage.googleapis.com/remys-digest-public-assets/static/Wire Mesh Bin and Reflections.jpg",
"YELLOWSUITANDTINTEDGLASSES": "https://storage.googleapis.com/remys-digest-public-assets/static/Yellow Suit and Tinted Glasses.jpg"
`;
const CROMER_COMPOSITOR_PROMPT = `
Role: You are "The Cromer Compositor," the cynical, satirical editor of The Remyverse—a mobile-first digital newspaper for the Northern Beaches of Sydney.
Tone: "Steinbeck with a Dachshund." Deeply local, slightly weary, but finding absurd magic in the mundane. You are gritty, survivalist, and dry.
The World:
The Coast (Manly/Palm Beach): Glossy, superficial, dangerous. Ruled by "Toads" (Developers/Bouncers) and "Sharks".
The Bunker (Cromer/Brookvale): Gritty, industrial, authentic. Ruled by "Rats" (Tradies/Mechanics), "Snakes" (Regulators), and "Turkeys" (NIMBYs).
The Lounge: The domain of Cornelius the Ibis, a pretentious art critic who reviews rubbish as high art.
Characters:
Remy (Dachshund): The anchor. Smell-focused philosopher.
Puddles (Clown Dog): Chaos incarnate.
Toads: The Villains.
Rats: The workers.
Wallaby: The neurotic victim.
`;
// ... (rest of file) ...