import google.generativeai as genai
import json
import os
import datetime
import sys

# --- Configuration ---
# API Key for Google Gemini
# Get one here: https://aistudio.google.com/app/apikey
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "AIzaSyBp7TQNTyUujVf3745RBxLXnWODZhF227E").strip()

# File Paths
WIRE_FILE = "wire_copy.json"
OUTPUT_DIR = "content"

def configure_genai():
    """Configures the Gemini API."""
    if GEMINI_API_KEY == "YOUR_GEMINI_KEY_HERE" or not GEMINI_API_KEY:
        print("[!] CRITICAL: Gemini API Key not set.")
        print("    Please set the GEMINI_API_KEY environment variable or edit the script.")
        return False
    
    genai.configure(api_key=GEMINI_API_KEY)
    return True

def load_wire_copy():
    """Loads the JSON data generated by scout.py."""
    if not os.path.exists(WIRE_FILE):
        print(f"[!] Error: {WIRE_FILE} not found. Run scout.py first.")
        return None
    
    try:
        with open(WIRE_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data
    except json.JSONDecodeError as e:
        print(f"[!] Error decoding JSON: {e}")
        return None

def construct_prompt(data):
    """
    Constructs the prompt for the LLM based on wire_copy data.
    """
    timestamp = data.get("timestamp", "Unknown Date")
    
    # --- Logic 1: Handle The Receipt ---
    receipt = data.get("receipt", {})
    if receipt.get("status") == "failed":
        receipt_context = "The transparency data is currently offline. The Duopoly is hiding their tracks."
    else:
        bill = receipt.get("bill_title", "Unknown Bill")
        result = receipt.get("vote_result", "Unknown Result")
        alignment = receipt.get("duopoly_check", "Unknown Alignment")
        receipt_context = (
            f"FACTUAL POLITICAL DATA (THE RECEIPT):\n"
            f"Bill: {bill}\n"
            f"Result: {result}\n"
            f"Bipartisan Agreement: {alignment}\n"
            f"Instruction: Use this specific vote to mock the illusion of choice in the political system."
        )

    # --- Logic 2: Inject Distractions ---
    # Prime Local (Manly Observer)
    local_headlines = data.get("red_balloon", {}).get("prime_local", {}).get("headlines", [])
    local_text = "\n".join([f"- {h}" for h in local_headlines])
    
    # Elsewhere Troppo (NT News/Chaos)
    troppo_headlines = data.get("red_balloon", {}).get("elsewhere_troppo", {}).get("headlines", [])
    troppo_text = "\n".join([f"- {h}" for h in troppo_headlines])

    # --- Build the Full Prompt ---
    prompt = f"""
    You are 'The Compositor', the cynical, satirical AI editor of 'The Remyverse'.
    
    OBJECTIVE:
    Write a complete HTML article for today's edition ({timestamp}).
    The article must weave together factual political despair with chaotic local distractions.
    
    --- SOURCE MATERIAL ---
    
    {receipt_context}
    
    LOCAL DISTRACTIONS (The Northern Beaches Bubble):
    {local_text}
    
    NATIONAL CHAOS (The 'Troppo' Factor):
    {troppo_text}
    
    --- WRITING GUIDELINES ---
    1. HEADLINE: Create a punchy, satirical headline that mixes the political vote with a chaotic distraction.
    2. TONE: Dry, Australian, matter-of-fact but absurd. 
    3. STRUCTURE:
       - An introductory paragraph mocking the political 'Receipt' (or lack thereof).
       - A section titled "Meanwhile, in the Bubble" covering the Local news.
       - A section titled "Going Troppo" covering the chaotic/weird news.
       - A cynical conclusion.
    4. FORMAT: Return ONLY valid HTML code inside <body> tags. Do not include ```html blocks or markdown. Use <h2>, <p>, <ul>, <li> tags.
       - Add a CSS class 'article-container' to the main wrapper.
       - Add a class 'satire-warning' to a small footer disclaimer.
    """
    return prompt

def generate_article(prompt):
    """Calls the Gemini API to generate the content."""
    print("[*] Commissioning article from Gemini...")
    try:
        model = genai.GenerativeModel('gemini-2.0-flash')
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"[!] API Generation Error: {e}")
        return None

def save_html(content, timestamp):
    """Saves the generated HTML to a file."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
    
    # Format filename: YYYY-MM-DD_edition.html
    try:
        date_str = datetime.datetime.strptime(timestamp, "%Y-%m-%d %H:%M:%S").strftime("%Y-%m-%d")
    except ValueError:
        date_str = datetime.date.today().isoformat()
        
    filename = f"{OUTPUT_DIR}/{date_str}_edition.html"
    
    # Simple HTML wrapper if the model returned just the body
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>The Remyverse: {date_str}</title>
        <style>
            body {{ font-family: 'Courier New', Courier, monospace; background-color: #f4f4f4; color: #333; padding: 20px; }}
            .article-container {{ max-width: 800px; margin: 0 auto; background: #fff; padding: 40px; border: 1px solid #ddd; box-shadow: 5px 5px 0px rgba(0,0,0,0.1); }}
            h1 {{ font-size: 2.5em; text-transform: uppercase; border-bottom: 2px solid #333; padding-bottom: 10px; }}
            h2 {{ color: #d32f2f; margin-top: 30px; }}
            .satire-warning {{ font-size: 0.8em; color: #777; margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; text-align: center; }}
        </style>
    </head>
    <body>
        {content}
    </body>
    </html>
    """
    
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(full_html)
        print(f"[+] Article published: {filename}")
    except IOError as e:
        print(f"[!] Failed to save HTML: {e}")

def main():
    if not configure_genai():
        return

    # 1. Load Data
    data = load_wire_copy()
    if not data:
        return

    # 2. Construct Prompt
    prompt = construct_prompt(data)
    
    # 3. Generate Content
    article_html = generate_article(prompt)
    
    # 4. Save Output
    if article_html:
        # Clean up markdown code blocks if the model added them
        article_html = article_html.replace("```html", "").replace("```", "")
        save_html(article_html, data.get("timestamp"))

if __name__ == "__main__":
    main()