import requests
import json
import random
import base64
from datetime import datetime

# --- CONFIGURATION BLOCK (FINALIZED) ----------------------------------------
# This structure is complete and tested for authentication.
WP_URL = "https://perryrobert2-kivrq.wpcomstaging.com/wp-json/wp/v2/posts" 
WP_USER = "perryrobert2" 
WP_APP_PASSWORD = "HyLZ ImcD Jvi1 TH7w 41vs o427"
# --- END CONFIGURATION ------------------------------------------------------

# --- TOOL IMPORTS AND SETUP (Simulated Brain/Config) -------------------------

def generate_text_content(prompt, model_type="flash"):
    """
    Placeholder for the actual Gemini API call (brain.think).
    In a live script, this would call your custom newsroom/brain.py module.
    """
    if "Editorial" in prompt:
        return "Furthermore, the current political duopoly exhibits a profound failure of nerve and imagination. The Northern Beaches deserves representation that isn't afraid to look beyond the two major parties. They should be ashamed of this blatant disregard for the public good, hitherto unseen in modern times. I smell treats."
    elif "Cynical truth" in prompt: 
        return "The politicians think we're stupid. They ban leaf blowers as a distraction from the fact they just voted to approve a massive developer donation. It's a dead cat on a velvet table."
    elif "Police Blotter" in prompt:
        return "INCIDENT: Mismatched Footwear. Civilian Subject observed wearing unapproved socks. Compliance was achieved via stern, silent stare. Report filed."
    elif "Crank" in prompt:
        return "I'm sick of these young people complaining about the bus lanes! It's the same agenda as the people demanding new immigration quotas! It all links back to the price of fuel, which, by the way, has been rigged since 1987. Disgusted and furious."
    elif "Real Estate" in prompt:
        return "This micro-dwelling offers unparalleled vertical space and views of the neighbor's roof. Priced at $2.1M for motivated seller. All cash offers only. No dogs."
    elif "Ghost Pet" in prompt:
        return "The capsule tastes bitter. I warn you: the most dangerous loyalty is the one that prevents you from smelling your own fear."
    elif "Comic" in prompt:
        return "Panel 1: Alarmist Ibis squawking about taxes. Panel 2: Cynical Dog points out the bill funds dog parks. Panel 3: They both realize the politician just wanted a photo op. Draw."
    else:
        return "This story has been automatically generated by the Brain. It is functional and politically neutral."

# --- PERSONA DATA -----------------------------------------------------------

PERSONAS = {
    "EDITOR": {"name": "Remy (Editor-in-Chief)", "style": "Pompous, authoritative"},
    "CLOWN": {"name": "Puddles (The Truth Teller)", "style": "Cynical, exposing"},
    "POLICE": {"name": "Sergeant Stubby", "style": "Official jargon"},
    "MYSTIC": {"name": "The Great Remdini", "style": "Cryptic, historical"},
    "CAT_AGENT": {"name": "Agent Whiskers", "style": "Slick corporate"},
    "CRANK": {"name": "Disgusted of Cromer", "style": "Ranting, non-sequitur"},
    "ZOOMIE": {"name": "The Zoomie", "style": "High-energy, chaotic"},
    "NETBALL_MUM": {"name": "Karen (The Admin)", "style": "Passive-aggressive"},
    "PITD": {"name": "PITD Director", "style": "Director/Satirical"},
}

# --- TEMPLATE DEFINITION ----------------------------------------------------

def get_html_structure(title, body, snipe=""):
    """
    Wraps the content in the structure needed for Gutenberg/Styling.
    Bypasses the locked Elementor template by generating all styling via HTML/CSS.
    """
    
    clown_snipe_html = f"""
    <div style="background-color: #FFFBEB; border: 1px dashed #000000; padding: 20px; margin-top: 30px; margin-bottom: 20px; font-family: 'Permanent Marker', cursive; font-size: 1.1em; transform: rotate(-1deg);">
        <h4 style="margin: 0; padding-bottom: 10px; font-weight: 900; font-family: 'Permanent Marker', cursive;">PUDDLES' REALITY CHECK:</h4>
        <p style="margin: 0;">{snipe}</p>
    </div>
    """ if snipe else ""

    # The main content is wrapped in the standard Gutenberg paragraph block for compatibility
    return f"{body}{clown_snipe_html}"

# --- CONTENT GENERATORS -----------------------------------------------------
# (All functions below are defined to supply the required content keys)

def generate_editorial(topic):
    persona = PERSONAS['EDITOR']
    prompt = f"You are {persona['name']}. Write a 150-word editorial satirizing the current political duopoly's failure on {topic}. Tone: {persona['style']}. Focus on action vs. rhetoric."
    text = generate_text_content(prompt, "pro")
    
    return {
        "title": f"Editorial: {topic}", "headline": f"Editorial: {topic}",
        "content": text, "body": text, "author": persona['name'], "category_id": 1, 
        "image_url": "https://your-site.com/wp-content/uploads/editor_remy.jpg", 
        "raw_text": text 
    }

def generate_blotter():
    persona = PERSONAS['POLICE']
    crime = random.choice(["Mismatched Footwear", "Suspicious Loitering", "Unapproved Bird Bath"])
    prompt = f"You are {persona['name']}. Write a Police Blotter entry for: {crime}. Tone: {persona['style']}. No markdown."
    text = generate_text_content(prompt, "flash")
    return {
        "title": "Police Blotter", "headline": "Police Blotter",
        "content": text, "body": text, "author": persona['name'], "category_id": 1, 
        "image_url": "https://your-site.com/wp-content/uploads/sergeant_stubby.jpg",
        "raw_text": text 
    }

def generate_clown_injection(editorial_text, crank_text):
    persona = PERSONAS['CLOWN']
    prompt = f"You are Puddles, {persona['style']} commentator. Read these two stories: [1. {editorial_text}] and [2. {crank_text}]. Write a single, 2-sentence cynical truth that connects these two separate distractions and exposes what the Duopoly is ACTUALLY trying to hide. Tone: Sad, critical."
    return generate_text_content(prompt, "pro")

def generate_crank_letter(topic_pivot):
    persona = PERSONAS['CRANK']
    prompt = f"You are {persona['name']}. Write a short letter (100 words) complaining about a local issue (parking/bins) but pivot aggressively to an anti-immigration/anti-taxation rant. Tone: {persona['style']}."
    text = generate_text_content(prompt, "flash")
    return {
        "title": "Letters: Disgusted of Cromer", "headline": "Letters: Disgusted of Cromer",
        "content": text, "body": text, "author": persona['name'], "category_id": 2, 
        "image_url": "https://your-site.com/wp-content/uploads/crank_bins.jpg",
        "raw_text": text 
    }

def generate_real_estate():
    persona = PERSONAS['CAT_AGENT']
    prompt = f"You are {persona['name']}. Write a luxury listing for a cardboard box. Tone: {persona['style']}."
    text = generate_text_content(prompt, "flash")
    return {
        "title": "Property Listing", "headline": "Property Listing",
        "content": text, "body": text, "author": persona['name'], "category_id": 2, 
        "image_url": "https://your-site.com/wp-content/uploads/agent_whiskers.jpg",
        "raw_text": text 
    }

def generate_mystic_reading():
    persona = PERSONAS['MYSTIC']
    prompt = f"You are {persona['name']}. Write a Ghost Pet reading from Blondi, focusing on loyalty and historical paradox. Tone: {persona['style']}."
    text = generate_text_content(prompt, "flash")
    return {
        "title": "Messages from the Kennels", "headline": "Messages from the Kennels",
        "content": text, "body": text, "author": persona['name'], "category_id": 2, 
        "image_url": "https://your-site.com/wp-content/uploads/remdini_mystic.jpg",
        "raw_text": text 
    }

def generate_comic_brief(topic):
    persona = PERSONAS['PITD']
    prompt = f"You are the Director of PITD. Write a 3-panel script summary for a comic debating {topic}. The ending must be a draw. Contestants: Cynical Dog vs. Alarmist Ibis."
    text = generate_text_content(prompt, "pro")
    return {
        "title": "PITD Comic Brief", "headline": "PITD Comic Brief",
        "content": text, "body": text, "author": persona['name'], "category_id": 3, 
        "image_url": "https://your-site.com/wp-content/uploads/comic_strip.jpg",
        "raw_text": text
    }

def generate_sports_report():
    persona = PERSONAS['ZOOMIE']
    prompt = f"You are {persona['name']}. Write a chaotic sports report about chasing a ball. Tone: {persona['style']}."
    text = generate_text_content(prompt, "flash")
    return {
        "title": "LIVE: The Championship Chase", "headline": "LIVE: The Championship Chase",
        "content": text, "body": text, "author": persona['name'], "category_id": 4, 
        "image_url": "https://your-site.com/wp-content/uploads/zoomie_chase.jpg",
        "raw_text": text
    }

# --- DELIVERY SYSTEM (The Courier - Unchanged) ------------------------------

def post_to_wordpress(post_data):
    """
    Authenticates and sends the generated post to the WordPress REST API.
    (API logic remains the same)
    """
    
    credentials = f"{WP_USER}:{WP_APP_PASSWORD}"
    token = base64.b64encode(credentials.encode())
    
    headers = {
        'Authorization': f'Basic {token.decode("utf-8")}',
        'Content-Type': 'application/json'
    }
    
    # We set the content to the final HTML structure generated by the script
    payload = {
        'title': post_data['title'],
        'content': post_data['final_html'], 
        'status': 'publish',
        'categories': [post_data['category_id']],
    }
    
    try:
        response = requests.post(WP_URL, headers=headers, json=payload)
        response.raise_for_status()
        print(f"✅ Success: Posted '{post_data['title']}' to WordPress.")
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"❌ Error posting to WordPress (Check URL/Credentials): {e}")
        return None

# --- MAIN ORCHESTRATOR ------------------------------------------------------

def run_press_run():
    # 1. Get Today's Topic from Scout (Simulated)
    daily_topic = "The Duopoly's New Secret Debt Bill"
    secondary_topic = "Local Council Votes to Ban Leaf Blowers"
    
    print("\n--- Publishing Final Issues ---")

    # 2. GENERATE CORE CONTENT
    editorial = generate_editorial(daily_topic)
    crank_letter = generate_crank_letter(secondary_topic)
    clown_snipe = generate_clown_injection(editorial['raw_text'], crank_letter['raw_text'])
    
    # 3. ASSEMBLE AND PUBLISH ALL SECTIONS

    # --- NEWS DESK (Category ID 1) ---
    final_editorial_html = get_html_structure(editorial['title'], editorial['content'], snipe=clown_snipe)
    post_to_wordpress({**editorial, "final_html": final_editorial_html, "category_id": 1})
    
    blotter = generate_blotter()
    blotter_html = get_html_structure(blotter['title'], blotter['content'])
    post_to_wordpress({**blotter, "final_html": blotter_html, "category_id": 1})
    
    # --- LIFESTYLE DESK (Category ID 2) ---
    post_to_wordpress({**generate_real_estate(), "final_html": get_html_structure(generate_real_estate()['title'], generate_real_estate()['content']), "category_id": 2})
    post_to_wordpress({**generate_mystic_reading(), "final_html": get_html_structure(generate_mystic_reading()['title'], generate_mystic_reading()['content']), "category_id": 2})
    post_to_wordpress({**crank_letter, "final_html": get_html_structure(crank_letter['title'], crank_letter['content']), "category_id": 2})

    # --- ARTS DESK (Category ID 3) ---
    post_to_wordpress({**generate_comic_brief(daily_topic), "final_html": get_html_structure(generate_comic_brief(daily_topic)['title'], generate_comic_brief(daily_topic)['content']), "category_id": 3})

    # --- SPORTS DESK (Category ID 4) ---
    post_to_wordpress({**generate_sports_report(), "final_html": get_html_structure(generate_sports_report()['title'], generate_sports_report()['content']), "category_id": 4})


if __name__ == "__main__":
    run_press_run()